// scripts/generate-wgle.js
const fs = require("fs");
const path = require("path");
const acorn = require("acorn");
const walk = require("acorn-walk").simple;

function generateWGLE() {
  const corePath = path.resolve("src/core/index.js");
  const outputPath = path.resolve("src/WGLE.js");

  const coreCode = fs.readFileSync(corePath, "utf-8");
  const ast = acorn.parse(coreCode, { ecmaVersion: "latest", sourceType: "module" });

  const exports = [];
  walk(ast, {
    ExportNamedDeclaration(node) {
      if (node.declaration?.type === "FunctionDeclaration") {
        exports.push(node.declaration.id.name);
      }
    },
  });

  const generated = `
// ✅ Auto-generated by generate-wgle.js
import * as Core from './core/index.js';

class WGLE {
  constructor(canvas, options = {}) {
    this.canvas = canvas;
    this.gl = Core.createWebGlContext(canvas, options);
    this.width = canvas.width;
    this.height = canvas.height;
  }
${exports
    .map(
      (fn) => `
  ${fn}(...args) {
    return Core.${fn}.call(this, ...args);
  }`
    )
    .join("\n")}
}

export { WGLE };
`;

  fs.writeFileSync(outputPath, generated.trimStart(), "utf-8");
  console.log(`✅ WGLE.js generated with ${exports.length} methods.`);
}

// برای export به rollup:
module.exports = generateWGLE;
